spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: hmgics.board.model
  configuration:
    map-underscore-to-camel-case: true
